#!/usr/bin/env bash

##############################################################################
##
##  Changelog creation script for use with Git Shell & Drone.io
##  Created by Funwayguy for Void Decay
##
##############################################################################

# Create document for update notice
echo $ver_num > version.txt
echo "http://minecraft.curseforge.com/mc-mods/231876-void-decay" >> version.txt
git log -1 --pretty=format:"%B" >> version.txt